# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
warnings_are_errors: false
#cache: packages
before_install:
  - Rscript -e 'install.packages("dplyr", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("DBI", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("assertthat", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("R6", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("Rcpp", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("magrittr", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("tibble", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("ggplot2", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("gtable", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("scales", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("munsell", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("colorspace", lib="/home/travis/R-bin/lib/R/library/")'
install:
  - Rscript -e "0" --args --bootstrap-packrat
  - R -e "packrat::restore(restart = FALSE)"
cache:
  directories: 
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true
